- name: variables in ansible
  hosts: mongodb
  vars: # This is play level variables, map
    COURSE: DevOps
    DURATION: 110 Hours
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, Iam learning Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, Iam learning {{COURSE}} and Duration is {{DURATION}}"