- name: variables at task level
  hosts: localhost
  vars:                 #these variables at parent level or play level 
  - money: "100000 RS"
    land: "100 hectars"
  tasks: 
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and override
    vars: 
    - money: "200000 RS"
      houses: "3 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"    
