- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # Whenever you want to run linux commands directly i.e in the case ansible module is not available
    # When the user does not exist, ansible will treat this as failure and comes out by default, So we have to ignore errors.
    ansible.builtin.command: id roboshop
    register: output # Here output is name of the variable
    ignore_errors: true # ansible will proceed even it faces with error at this stage
    # So Ansible will run this { id roboshop } command and it will store the output in this output variable.
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop  # When user doesnot exit creates the roboshop user based on when output.rc != 0
    become: yes # give sudo access for this task to create the roboshop user
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0


