- name: if we want to install multiple packages using Ansible we can use for-loop
  hosts: mongodb
  become: yes # to get the sudo access
  tasks: 
  - name: install package
    ansible.builtin.yum: # this is the collection or module to install the packages
      name: "{{item.name}}"
      state: "{{item.state}}"
    # list of map
    loop:
    - {name: 'nginx', state: 'absent'} # here i want to remove nginx that's why we have status as absent
    - {name: 'postfix', state: 'istalled'} # here i want to install postfix package
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'installed'}



